export const categoryKeywords = {
    crypto: [
      "bitcoin",
      "btc",
      "ethereum",
      "eth",
      "solana",
      "crypto",
      "blockchain",
      "coin",
      "token",
      "nft",
      "defi",
      "altcoin",
      "web3",
    ],
    politics: [
      "president",
      "election",
      "trump",
      "biden",
      "democrat",
      "republican",
      "congress",
      "senate",
      "government",
      "war",
    ],
    economy: [
      "recession",
      "inflation",
      "fed",
      "interest rate",
      "gdp",
      "economy",
      "stock",
      "unemployment",
    ],
    sports: [
      "super bowl",
      "nfl",
      "nba",
      "world cup",
      "olympics",
      "football",
      "basketball",
      "soccer",
      "tennis",
      "ufc",
    ],
  };